<?php

namespace App\Http\Controllers\Visitor;

use App\Http\Controllers\Controller;
use Inertia\Inertia;


class OfficeController extends Controller
{
    private static function offices(): array
    {
        return [
            'ancillary-service-unit' => [
                'id'          => 'ancillary-service-unit',
                'name'        => 'Ancillary Service Unit',
                'description' => 'Provides ancillary and general support services for the city hall operations.',
                'floor'       => 1,
                'room'        => 'Room 102',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1001',
                'email'       => 'asu@davaocity.gov.ph',
                'head'        => 'Unit Head',
                'services'    => ['Support Services', 'Maintenance Coordination', 'Utility Management'],
            ],
            'barangay-cultural-affairs' => [
                'id'          => 'barangay-cultural-affairs',
                'name'        => 'Barangay and Cultural Communities Affairs Division',
                'description' => 'Handles barangay relations and programs for cultural community groups in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 202',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1002',
                'email'       => 'bcca@davaocity.gov.ph',
                'head'        => 'Division Head',
                'services'    => ['Barangay Coordination', 'Cultural Programs', 'Indigenous Peoples Affairs'],
            ],
            'business-bureau' => [
                'id'          => 'business-bureau',
                'name'        => 'Business Bureau',
                'description' => 'Issuance and renewal of business permits and licenses for Davao City.',
                'floor'       => 1,
                'room'        => 'Room 120',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1003',
                'email'       => 'bb@davaocity.gov.ph',
                'head'        => 'Bureau Head',
                'services'    => ['New Business Permit', 'Business Permit Renewal', 'Closure Permit', "Mayor's Permit"],
            ],
            'city-accountants-office' => [
                'id'          => 'city-accountants-office',
                'name'        => "City Accountant's Office",
                'description' => 'Manages city accounting, financial records, and disbursements.',
                'floor'       => 3,
                'room'        => 'Room 301',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1004',
                'email'       => 'accounting@davaocity.gov.ph',
                'head'        => 'City Accountant',
                'services'    => ['Financial Reporting', 'Disbursement', 'Pre-Audit', 'Payroll Processing'],
            ],
            'city-administrators-office' => [
                'id'          => 'city-administrators-office',
                'name'        => "City Administrator's Office",
                'description' => 'Oversees general administration and coordinates all city government operations.',
                'floor'       => 3,
                'room'        => 'Room 302',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1005',
                'email'       => 'administrator@davaocity.gov.ph',
                'head'        => 'City Administrator',
                'services'    => ['Administrative Coordination', 'Policy Implementation', 'Inter-office Liaison'],
            ],
            'city-agriculturists-office' => [
                'id'          => 'city-agriculturists-office',
                'name'        => "City Agriculturist's Office",
                'description' => 'Promotes agricultural development, food security, and farmer welfare in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 203',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1006',
                'email'       => 'agriculture@davaocity.gov.ph',
                'head'        => 'City Agriculturist',
                'services'    => ['Agricultural Extension', 'Farmers Assistance', 'Food Security Programs', 'Crop Production Support'],
            ],
            'city-anti-drug-abuse-council' => [
                'id'          => 'city-anti-drug-abuse-council',
                'name'        => 'City Anti-Drug Abuse Council',
                'description' => 'Leads anti-drug advocacy, prevention programs, and coordination with law enforcement.',
                'floor'       => 2,
                'room'        => 'Room 204',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1007',
                'email'       => 'cadac@davaocity.gov.ph',
                'head'        => 'CADAC Head',
                'services'    => ['Drug Prevention Programs', 'Community Advocacy', 'Rehabilitation Referral'],
            ],
            'city-archives-records-office' => [
                'id'          => 'city-archives-records-office',
                'name'        => 'City Archives and Records Office',
                'description' => 'Preserves, manages, and provides access to official city government records and archives.',
                'floor'       => 1,
                'room'        => 'Room 103',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1008',
                'email'       => 'archives@davaocity.gov.ph',
                'head'        => 'City Archivist',
                'services'    => ['Records Retrieval', 'Document Certification', 'Archives Access', 'Records Management'],
            ],
            'city-assessors-office' => [
                'id'          => 'city-assessors-office',
                'name'        => "City Assessor's Office",
                'description' => 'Appraisal and assessment of real property for taxation purposes in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 205',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1009',
                'email'       => 'assessor@davaocity.gov.ph',
                'head'        => 'City Assessor',
                'services'    => ['Tax Declaration', 'Property Assessment', 'Transfer of Ownership', 'Property Records'],
            ],
            'city-budget-office' => [
                'id'          => 'city-budget-office',
                'name'        => 'City Budget Office',
                'description' => 'Prepares and manages the annual city budget and monitors fund utilization.',
                'floor'       => 3,
                'room'        => 'Room 303',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1010',
                'email'       => 'budget@davaocity.gov.ph',
                'head'        => 'City Budget Officer',
                'services'    => ['Budget Preparation', 'Fund Allocation', 'Budget Monitoring', 'Financial Planning'],
            ],
            'city-college-of-davao' => [
                'id'          => 'city-college-of-davao',
                'name'        => 'City College of Davao',
                'description' => 'City-run higher education institution offering affordable tertiary education to Davao residents.',
                'floor'       => 1,
                'room'        => 'Admin Building',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1011',
                'email'       => 'ccd@davaocity.gov.ph',
                'head'        => 'College President',
                'services'    => ['Enrollment', 'Scholarships', 'Academic Records', 'Student Services'],
            ],
            'city-cooperative-development-office' => [
                'id'          => 'city-cooperative-development-office',
                'name'        => 'City Cooperative Development Office',
                'description' => 'Promotes cooperative formation, registration, and development in the city.',
                'floor'       => 2,
                'room'        => 'Room 206',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1012',
                'email'       => 'cooperative@davaocity.gov.ph',
                'head'        => 'Cooperative Officer',
                'services'    => ['Cooperative Registration', 'Training', 'Technical Assistance', 'Cooperative Financing'],
            ],
            'city-economic-enterprise-office' => [
                'id'          => 'city-economic-enterprise-office',
                'name'        => 'City Economic Enterprise Office',
                'description' => 'Manages city-owned economic enterprises and public markets.',
                'floor'       => 2,
                'room'        => 'Room 207',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1013',
                'email'       => 'ceeo@davaocity.gov.ph',
                'head'        => 'CEEO Head',
                'services'    => ['Market Stall Management', 'Enterprise Monitoring', 'Revenue Management'],
            ],
            'city-engineers-office' => [
                'id'          => 'city-engineers-office',
                'name'        => "City Engineer's Office",
                'description' => 'Building permits, infrastructure projects, and engineering services for the city.',
                'floor'       => 2,
                'room'        => 'Room 210',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1014',
                'email'       => 'engineering@davaocity.gov.ph',
                'head'        => 'City Engineer',
                'services'    => ['Building Permit', 'Occupancy Permit', 'Infrastructure Planning', 'Engineering Inspection'],
            ],
            'city-environment-natural-resources-office' => [
                'id'          => 'city-environment-natural-resources-office',
                'name'        => 'City Environment and Natural Resources Office',
                'description' => 'Oversees environmental protection and natural resource conservation in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 208',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1015',
                'email'       => 'cenro@davaocity.gov.ph',
                'head'        => 'CENRO Head',
                'services'    => ['Environmental Clearance', 'Tree Cutting Permit', 'Environmental Programs', 'Waste Management'],
            ],
            'city-general-services-office' => [
                'id'          => 'city-general-services-office',
                'name'        => 'City General Services Office',
                'description' => 'Manages city properties, equipment, and general maintenance services.',
                'floor'       => 1,
                'room'        => 'Room 104',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1016',
                'email'       => 'gso@davaocity.gov.ph',
                'head'        => 'GSO Head',
                'services'    => ['Property Management', 'Procurement', 'Equipment Maintenance', 'Janitorial Services'],
            ],
            'city-health-office' => [
                'id'          => 'city-health-office',
                'name'        => 'City Health Office',
                'description' => 'Public health programs, clinics, sanitary permits, and health certifications.',
                'floor'       => 1,
                'room'        => 'Room 110',
                'hours'       => 'Mon–Fri, 7:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1017',
                'email'       => 'health@davaocity.gov.ph',
                'head'        => 'City Health Officer',
                'services'    => ['Medical Certificate', 'Vaccination', 'Health Card', 'Sanitary Permit', 'Prenatal Care'],
            ],
            'city-information-technology-center' => [
                'id'          => 'city-information-technology-center',
                'name'        => 'City Information Technology Center',
                'description' => "Manages the city's IT infrastructure, digital systems, and online services.",
                'floor'       => 3,
                'room'        => 'Room 304',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1018',
                'email'       => 'citc@davaocity.gov.ph',
                'head'        => 'CITC Head',
                'services'    => ['System Support', 'Network Management', 'E-Government Services', 'Data Management'],
            ],
            'city-information-office' => [
                'id'          => 'city-information-office',
                'name'        => 'City Information Office',
                'description' => 'Handles public information, media relations, and official communications of the city.',
                'floor'       => 1,
                'room'        => 'Room 105',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1019',
                'email'       => 'info@davaocity.gov.ph',
                'head'        => 'City Information Officer',
                'services'    => ['Press Releases', 'Public Announcements', 'Media Coordination', 'Publication'],
            ],
            'city-legal-office' => [
                'id'          => 'city-legal-office',
                'name'        => 'City Legal Office',
                'description' => 'Provides legal counsel, opinions, and representation for the city government.',
                'floor'       => 3,
                'room'        => 'Room 305',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1020',
                'email'       => 'legal@davaocity.gov.ph',
                'head'        => 'City Legal Officer',
                'services'    => ['Legal Consultation', 'Contract Review', 'Legal Opinions', 'Litigation Support'],
            ],
            'city-library-information-center' => [
                'id'          => 'city-library-information-center',
                'name'        => 'City Library and Information Center',
                'description' => 'Public library offering reading materials, research resources, and information services.',
                'floor'       => 1,
                'room'        => 'Room 106',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1021',
                'email'       => 'library@davaocity.gov.ph',
                'head'        => 'City Librarian',
                'services'    => ['Library Access', 'Research Assistance', 'Book Lending', 'Digital Resources'],
            ],
            'city-planning-development-office' => [
                'id'          => 'city-planning-development-office',
                'name'        => 'City Planning and Development Office',
                'description' => 'Zoning clearances, land use planning, and development coordination for Davao City.',
                'floor'       => 2,
                'room'        => 'Room 209',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1022',
                'email'       => 'cpdo@davaocity.gov.ph',
                'head'        => 'City Planning Officer',
                'services'    => ['Zoning Clearance', 'Land Use Planning', 'Development Permit', 'Zoning Certification'],
            ],
            'city-social-welfare-development-office' => [
                'id'          => 'city-social-welfare-development-office',
                'name'        => 'City Social Welfare and Development Office',
                'description' => 'Social welfare programs, assistance to indigents, and protective services for vulnerable residents.',
                'floor'       => 1,
                'room'        => 'Room 115',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1023',
                'email'       => 'cswdo@davaocity.gov.ph',
                'head'        => 'CSWDO Head',
                'services'    => ['Financial Assistance', 'Solo Parent ID', 'PWD ID', '4Ps Coordination', 'AICS'],
            ],
            'city-tourism-operations-office' => [
                'id'          => 'city-tourism-operations-office',
                'name'        => 'City Tourism Operations Office',
                'description' => 'Tourism promotion, accreditation of establishments, and visitor information services.',
                'floor'       => 1,
                'room'        => 'Room 107',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1024',
                'email'       => 'tourism@davaocity.gov.ph',
                'head'        => 'Tourism Officer',
                'services'    => ['Tourism Accreditation', 'Visitor Information', 'Event Coordination', 'Tourism Promotion'],
            ],
            'city-transportation-traffic-management-office' => [
                'id'          => 'city-transportation-traffic-management-office',
                'name'        => 'City Transportation and Traffic Management Office',
                'description' => 'Traffic management, transport regulation, and road safety enforcement.',
                'floor'       => 2,
                'room'        => 'Room 211',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1025',
                'email'       => 'cttmo@davaocity.gov.ph',
                'head'        => 'CTTMO Head',
                'services'    => ['Franchise Permit', 'Traffic Violation', 'Transport Regulation', 'Road Safety Programs'],
            ],
            'city-treasurers-office' => [
                'id'          => 'city-treasurers-office',
                'name'        => "City Treasurer's Office",
                'description' => 'Collection of local taxes, fees, and other government revenues.',
                'floor'       => 1,
                'room'        => 'Room 110',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1026',
                'email'       => 'treasurer@davaocity.gov.ph',
                'head'        => 'City Treasurer',
                'services'    => ['Real Property Tax', 'Business Tax', 'Community Tax Certificate', 'Revenue Collection'],
            ],
            'city-veterinarians-office' => [
                'id'          => 'city-veterinarians-office',
                'name'        => "City Veterinarian's Office",
                'description' => 'Animal care, veterinary services, livestock programs, and rabies control.',
                'floor'       => 1,
                'room'        => 'Room 108',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1027',
                'email'       => 'veterinarian@davaocity.gov.ph',
                'head'        => 'City Veterinarian',
                'services'    => ['Veterinary Services', 'Animal Vaccination', 'Livestock Programs', 'Rabies Control'],
            ],
            'civil-registrars-office' => [
                'id'          => 'civil-registrars-office',
                'name'        => "Civil Registrar's Office",
                'description' => 'Handles birth, marriage, and death certificates and related civil documents for Davao City residents.',
                'floor'       => 1,
                'room'        => 'Room 105',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1028',
                'email'       => 'civilregistrar@davaocity.gov.ph',
                'head'        => 'City Civil Registrar',
                'services'    => ['Birth Certificate', 'Marriage Certificate', 'Death Certificate', 'CENOMAR', 'Late Registration'],
            ],
            'correspondence-record-division' => [
                'id'          => 'correspondence-record-division',
                'name'        => 'Correspondence and Record Division',
                'description' => 'Manages official correspondence routing and document records for the city government.',
                'floor'       => 2,
                'room'        => 'Room 212',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1029',
                'email'       => 'records@davaocity.gov.ph',
                'head'        => 'Division Head',
                'services'    => ['Document Routing', 'Official Correspondence', 'Record Filing', 'Mail Management'],
            ],
            'davao-city-central-911' => [
                'id'          => 'davao-city-central-911',
                'name'        => 'Davao City Central 911 Emergency',
                'description' => 'Centralized emergency response dispatch for police, fire, and medical assistance in Davao City.',
                'floor'       => 1,
                'room'        => 'Room GF-001',
                'hours'       => '24/7',
                'contact'     => '911',
                'email'       => 'central911@davaocity.gov.ph',
                'head'        => 'Operations Head',
                'services'    => ['Emergency Dispatch', 'Police Coordination', 'Fire Response', 'Medical Emergency'],
            ],
            'davao-city-housing-office' => [
                'id'          => 'davao-city-housing-office',
                'name'        => 'Davao City Housing Office',
                'description' => 'Implements socialized housing programs and resettlement for informal settler families.',
                'floor'       => 2,
                'room'        => 'Room 213',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1031',
                'email'       => 'housing@davaocity.gov.ph',
                'head'        => 'Housing Officer',
                'services'    => ['Housing Application', 'Resettlement Programs', 'Housing Assistance', 'Lot Allocation'],
            ],
            'davao-city-investment-promotion-center' => [
                'id'          => 'davao-city-investment-promotion-center',
                'name'        => 'Davao City Investment Promotion Center',
                'description' => 'Promotes investment opportunities and facilitates business development in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 214',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1032',
                'email'       => 'ipc@davaocity.gov.ph',
                'head'        => 'IPC Head',
                'services'    => ['Investment Facilitation', 'Business Matching', 'Incentive Processing', 'Investor Assistance'],
            ],
            'davao-city-muslim-affairs-office' => [
                'id'          => 'davao-city-muslim-affairs-office',
                'name'        => 'Davao City Muslim Affairs Office',
                'description' => 'Provides services and programs addressing the needs of the Muslim community in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 215',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1033',
                'email'       => 'muslimaffairs@davaocity.gov.ph',
                'head'        => 'Muslim Affairs Head',
                'services'    => ['Muslim Community Services', 'Halal Certification Assistance', 'Cultural Programs', 'Community Coordination'],
            ],
            'davao-city-treatment-rehabilitation-center' => [
                'id'          => 'davao-city-treatment-rehabilitation-center',
                'name'        => 'Davao City Treatment and Rehabilitation Center for Drug Dependents',
                'description' => 'Provides drug treatment and rehabilitation services for drug dependents in Davao City.',
                'floor'       => 1,
                'room'        => 'Rehabilitation Building',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1034',
                'email'       => 'rehab@davaocity.gov.ph',
                'head'        => 'Center Head',
                'services'    => ['Drug Rehabilitation', 'Counseling', 'Aftercare Programs', 'Family Support'],
            ],
            'disaster-risk-reduction-management-office' => [
                'id'          => 'disaster-risk-reduction-management-office',
                'name'        => 'Disaster Risk Reduction and Management Office',
                'description' => 'Leads city-wide disaster preparedness, response, rehabilitation, and mitigation programs.',
                'floor'       => 1,
                'room'        => 'Room 109',
                'hours'       => '24/7',
                'contact'     => '(082) 227-1035',
                'email'       => 'drrmo@davaocity.gov.ph',
                'head'        => 'DRRMO Head',
                'services'    => ['Disaster Preparedness', 'Emergency Response', 'Evacuation Coordination', 'Hazard Mapping'],
            ],
            'educational-benefit-system-unit' => [
                'id'          => 'educational-benefit-system-unit',
                'name'        => 'Educational Benefit System Unit',
                'description' => 'Manages educational assistance, scholarships, and financial benefits for Davao City students.',
                'floor'       => 2,
                'room'        => 'Room 216',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1036',
                'email'       => 'ebsu@davaocity.gov.ph',
                'head'        => 'Unit Head',
                'services'    => ['Scholarship Application', 'Educational Assistance', 'Beneficiary Enrollment', 'Grants Management'],
            ],
            'human-resource-management-office' => [
                'id'          => 'human-resource-management-office',
                'name'        => 'Human Resource Management Office',
                'description' => 'Manages personnel records, recruitment, appointments, and employee welfare programs.',
                'floor'       => 3,
                'room'        => 'Room 306',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1037',
                'email'       => 'hrmo@davaocity.gov.ph',
                'head'        => 'HRMO Head',
                'services'    => ['Appointment Processing', 'Leave Management', 'Personnel Records', 'Employee Benefits'],
            ],
            'integrated-gender-development-division' => [
                'id'          => 'integrated-gender-development-division',
                'name'        => 'Integrated Gender and Development Division',
                'description' => 'Mainstreams gender-responsive policies and programs across all city government offices.',
                'floor'       => 2,
                'room'        => 'Room 217',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1038',
                'email'       => 'igdd@davaocity.gov.ph',
                'head'        => 'Division Head',
                'services'    => ['Gender Sensitivity Training', 'GAD Planning', "Women's Programs", 'Policy Advocacy'],
            ],
            'internal-audit-service-division' => [
                'id'          => 'internal-audit-service-division',
                'name'        => 'Internal Audit Service Division',
                'description' => 'Conducts internal audits to ensure fiscal accountability and compliance with regulations.',
                'floor'       => 3,
                'room'        => 'Room 307',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1039',
                'email'       => 'iasd@davaocity.gov.ph',
                'head'        => 'Division Head',
                'services'    => ['Internal Audit', 'Compliance Review', 'Financial Inspection', 'Risk Assessment'],
            ],
            'lingap' => [
                'id'          => 'lingap',
                'name'        => 'Lingap',
                'description' => 'Provides welfare assistance, livelihood support, and relief services to marginalized residents.',
                'floor'       => 1,
                'room'        => 'Room 111',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1040',
                'email'       => 'lingap@davaocity.gov.ph',
                'head'        => 'Lingap Head',
                'services'    => ['Welfare Assistance', 'Livelihood Programs', 'Relief Distribution', 'Crisis Intervention'],
            ],
            'madrasah-development-promotion-unit' => [
                'id'          => 'madrasah-development-promotion-unit',
                'name'        => 'Madrasah Comprehensive Development and Promotion Unit',
                'description' => 'Supports the development and promotion of madrasah education in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 218',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1041',
                'email'       => 'madrasah@davaocity.gov.ph',
                'head'        => 'Unit Head',
                'services'    => ['Madrasah Support', 'Teacher Training', 'Curriculum Assistance', 'Educational Programs'],
            ],
            'museo-dabawenyo' => [
                'id'          => 'museo-dabawenyo',
                'name'        => 'Museo Dabawenyo',
                'description' => "Davao City's official museum showcasing cultural heritage, history, and indigenous traditions.",
                'floor'       => 1,
                'room'        => 'GF – Museum Building',
                'hours'       => 'Mon–Sat, 9:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1042',
                'email'       => 'museo@davaocity.gov.ph',
                'head'        => 'Museum Curator',
                'services'    => ['Museum Tours', 'Cultural Exhibits', 'Heritage Programs', 'Educational Visits'],
            ],
            'office-for-senior-citizens-affairs' => [
                'id'          => 'office-for-senior-citizens-affairs',
                'name'        => 'Office for Senior Citizens Affairs',
                'description' => 'Issuance of senior citizen and PWD identification cards and delivery of related benefits.',
                'floor'       => 1,
                'room'        => 'Room GF-04',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1043',
                'email'       => 'osca@davaocity.gov.ph',
                'head'        => 'OSCA Head',
                'services'    => ['Senior Citizen ID', 'PWD ID', 'Discount Booklet', 'Senior Citizen Benefits'],
            ],
            'office-city-building-official' => [
                'id'          => 'office-city-building-official',
                'name'        => 'Office of the City Building Official',
                'description' => 'Issues building permits and enforces the National Building Code within Davao City.',
                'floor'       => 2,
                'room'        => 'Room 219',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1044',
                'email'       => 'buildingofficial@davaocity.gov.ph',
                'head'        => 'City Building Official',
                'services'    => ['Building Permit', 'Demolition Permit', 'Fencing Permit', 'Building Inspection', 'Occupancy Permit'],
            ],
            'peace-911' => [
                'id'          => 'peace-911',
                'name'        => 'Peace 911',
                'description' => 'Rapid peace and order response unit providing community safety and conflict resolution.',
                'floor'       => 1,
                'room'        => 'Room GF-05',
                'hours'       => '24/7',
                'contact'     => '(082) 227-1045',
                'email'       => 'peace911@davaocity.gov.ph',
                'head'        => 'Peace 911 Head',
                'services'    => ['Emergency Response', 'Community Patrol', 'Conflict Mediation', 'Peace and Order'],
            ],
            'public-employment-service-office' => [
                'id'          => 'public-employment-service-office',
                'name'        => 'Public Employment Service Office',
                'description' => 'Facilitates job placement, employment coordination, and labor market information services.',
                'floor'       => 1,
                'room'        => 'Room 112',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1046',
                'email'       => 'peso@davaocity.gov.ph',
                'head'        => 'PESO Manager',
                'services'    => ['Job Placement', 'Job Fair', 'Employment Referral', 'Labor Market Info'],
            ],
            'public-safety-security-office' => [
                'id'          => 'public-safety-security-office',
                'name'        => 'Public Safety and Security Office',
                'description' => 'Enforces public safety, manages security personnel, and coordinates law enforcement programs.',
                'floor'       => 1,
                'room'        => 'Room 113',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1047',
                'email'       => 'psso@davaocity.gov.ph',
                'head'        => 'PSSO Head',
                'services'    => ['Security Management', 'Safety Inspections', 'Community Safety Programs', 'Watchdog Services'],
            ],
            'sangguniang-panlungsod' => [
                'id'          => 'sangguniang-panlungsod',
                'name'        => 'Sangguniang Panlungsod',
                'description' => 'The legislative body of Davao City responsible for enacting local ordinances and resolutions.',
                'floor'       => 3,
                'room'        => 'Room 310',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1048',
                'email'       => 'sp@davaocity.gov.ph',
                'head'        => 'City Council Secretary',
                'services'    => ['Ordinance Filing', 'Resolution Requests', 'Legislative Sessions', 'Public Hearings'],
            ],
            'sports-development-division' => [
                'id'          => 'sports-development-division',
                'name'        => 'Sports Development Division',
                'description' => 'Develops sports programs, manages athletic training, and promotes sports culture in Davao City.',
                'floor'       => 2,
                'room'        => 'Room 220',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1049',
                'email'       => 'sports@davaocity.gov.ph',
                'head'        => 'Division Head',
                'services'    => ['Sports Registration', 'Athletic Training', 'Sports Events', 'Facility Booking'],
            ],
            'vices-regulation-unit' => [
                'id'          => 'vices-regulation-unit',
                'name'        => 'Vices Regulation Unit',
                'description' => 'Regulates establishments involved in vices and enforces related city ordinances.',
                'floor'       => 1,
                'room'        => 'Room 114',
                'hours'       => 'Mon–Fri, 8:00 AM – 5:00 PM',
                'contact'     => '(082) 227-1050',
                'email'       => 'vru@davaocity.gov.ph',
                'head'        => 'Unit Head',
                'services'    => ['Establishment Regulation', 'Permit Inspection', 'Compliance Monitoring', 'Ordinance Enforcement'],
            ],
        ];
    }

    public function show(string $officeId)
    {
        $offices = self::offices();

        abort_if(!isset($offices[$officeId]), 404);

        return Inertia::render('visitors/office', [
            'office' => $offices[$officeId],
        ]);
    }
}